config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  #root "users#index"

  resources :users

  post '/follow', to: 'followers#follow'
  post '/unfollow', to: 'followers#unfollow'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/follow.rb
class Follow < ApplicationRecord

    belongs_to :follower, foreign_key: :follower_id, class_name: "User"

    belongs_to :followed_user, foreign_key: :followed_user_id, class_name: "User"

end

app/models/user.rb
class User < ApplicationRecord

    has_many :received_follows, foreign_key: :followed_user_id, class_name: "Follow", dependent: :destroy

    has_many :followers, through: :received_follows, source: :follower, dependent: :destroy

    has_many :given_follows, foreign_key: :follower_id, class_name: "Follow"
  
    has_many :followings, through: :given_follows, source: :followed_user
    
end

app/controllers/api_application_controller.rb
class ApiApplicationController < ActionController::API

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

    helper_method :current_user
    
    def set_current_user
        @current_user ||= User.first
    end

end

app/controllers/followers_controller.rb
class FollowersController < ApplicationController
    before_action :set_current_user, only: [:follow, :unfollow]

    def follow
        @followed_user = params.require(:id_followed)
        if ! Follow.exists?(follower_id: @current_user[:id], followed_user_id: @followed_user)
            @follow_user = Follow.create!(follower_id: @current_user[:id], followed_user_id: @followed_user)
            if @follow_user.save
                redirect_to users_path
            end
        end
    end
    def unfollow
        @followed_user = params.require(:id_followed)
        if Follow.exists?(follower_id: @current_user[:id], followed_user_id: @followed_user)
            @unfollowed_user = Follow.find_by!(follower_id: @current_user[:id], followed_user_id: @followed_user)
            @unfollowed_user.destroy!
        end
        redirect_to users_path
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

    before_action :set_user, only: [:show, :edit, :update, :destroy]
    before_action :set_current_user, only: [:index]
    
    def index #ruta a /users
        @presenter = UserPresenter.new(params)
        @followornot = @current_user.followings
        respond_to do |format|
            format.json {render json: build_json_index}
            format.html
        end
    
    end

    #ruta /users/id
    def show; 
        @followed_users = @user.followings.pluck(:name)
        @followers = @user.followers.pluck(:name)
        respond_to do |format|
            format.json {render json: build_json_show}
            format.html
        end
    end

    def create #es un post del nuevo usuario
        @user = User.create(user_params)
        if @user.save
            redirect_to users_path
        end
    end

    def new #ruta /users/new apunta a vista para crear nuevo usuario
        @user = User.new
    end

    def edit; end

    def update
        if @user.update(user_params)
            redirect_to @user
        end
    end

    def destroy
        Follow.where(follower_id: @user[:id]).or(followed_user_id: @user[:id]).destroy_all
        @user.destroy!
        redirect_to users_path
    end

    private

    def set_user
        @user = User.find(params[:id])
    end

    def user_params
        params.require(:user).permit(:name,:age)
    end

    def build_json_index
    {
        user_list: @users,
        follower_count: @follower_count,
        following_count: @following_count
    }
    end

    def build_json_show
    {
        user: @user,
        followed_users: @followed_users ,
        followers: @followers
    }
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/followers_helper.rb
module FollowersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Follows</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/edit.html.erb
<%= form_with model: @user do |f| %>
    <h1>Editar Usuario: <%= @user.name %></h1>
    <%= f.label :name %>
    <%= f.text_field :name %>

    <%= f.label :age %>
    <%= f.text_field :age %>

    <%= f.submit %>
<% end %>

app/views/users/index.html.erb
<h1><%= t('users.users-list') %></h1>
<%= button_to t('users.add-user'), new_user_path , method: :get %>
<h1><%=t('users.popular-users')%></h1>
<% @presenter.populars.each do |pop| %>
  <p><%= pop.name %></p>
<% end %>
<%= form_with(model: @presenter.filter,url: users_path, method: :get) do |form| %>
  <%= form.text_field :name,value: params[:name] %>
  <%= form.number_field :min_follow, value: params[:min_follow] %>
  <%= form.number_field :max_follow, value: params[:max_follow] %>
  <%= form.submit %>
<% end %>
<% @presenter.users.each do |user| %>
  <div>
    <h2><%= user.name %></h2>
    <p><%= user.age %></p>
    <p><%=t('users.followed-users')%> <%= @presenter.follower_count[user.id]%></p>
    <p><%=t('users.following-users')%> <%= @presenter.following_count[user.id] %></p>
    <%= link_to t('users.see-user'),user_path(user.id) %>
    <% if @current_user != user%>
      <%= button_to t('users.delete'), user_path(user.id), method: :delete %>
      <% if @followornot.select {|follow| follow[:id] == user.id }.empty?%>
        <%= button_to t('users.follow'), '/follow', params: {id_followed: user.id  }, method: :post %> 
      <% else %>
        <%= button_to t('users.unfollow'), '/unfollow', params: {id_followed: user.id  }, method: :post %>
      <% end %>
    <% end %>
    
  </div>
<% end %>

app/views/users/new.html.erb
<h1>Nuevo Usuario</h1>
<%= form_with model: @user do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :age %>
  <%= f.text_field :age %>

  <%= f.submit %>
<% end %>

app/views/users/show.html.erb
<h1>Usuario: <%= @user.name %></h1>
<h1>Id: <%= @user.id %></h1>
<p>Edad: <%= @user.age %></p>
<%= button_to "Editar", edit_user_path(@user.id), method: :get %>
<%= button_to "Volver a Usuarios", users_path, method: :get %>

<h2><%=t('users.popular-users')%></h2>
<% @followers.each do |u| %>
    <p>Usuario: <%= u %></p>
<% end %>
<h2>Usuarios que sigo:</h2>
<% @followed_users.each do |u| %>
    <p>Usuario: <%= u %></p>
<% end %>